apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v6gmb8jwq-java-quarkus
  janus-idp.io/tekton: v6gmb8jwq-java-quarkus
  backstage.io/kubernetes-id: v6gmb8jwq-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v6gmb8jwq-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
